### PR TITLE
Feature/post styling

### PR DESCRIPTION
**Pull request by BAZBOT123**
I have completed all objectives on the ticket. Click below for reference: 
https://github.com/boolean-uk/team-dev-client/projects/1#card-81200200

### CODE REVIEW

**Review by alsyoufomar — APPROVED** [review]
Looks cushty mush!

**Comment by mikemherron** [comment]
Hey Barry, could you add a screenshot of the styling changes to the PR? For visual changes, it's really helpful for anyone reviewing!

**Comment by BAZBOT123** [comment]
here is a screenshot of the proposed styling changed implemented on the live server: 
Screenshot 2022-05-04 at 11 17 23

**Comment by BAZBOT123** [comment]
Updates have been made for the product owner. 

• Remove background on the individual posts and the content
• make the border a very slight grey
• make the the post content text slightly larger than the author and time
• remove "Status:"

See image below for reference: 
Screenshot 2022-05-04 at 15 55 18

**Pull request merged**
