### PR TITLE
restyle css to avoid blindness

### PR DESCRIPTION
**Pull request by nicopicchio**
restyle form layout and color scheme

### CODE REVIEW

**Comment by dearshrewdwit** [comment]
@mikemherron owns the requirements for this cohort - so clarify with him what the colour theme is/if there's a style guide.

If there's a change to the theme, make sure it's documented so other team members can continue and use the same styles.

**Comment by mikemherron** [comment]
Can we add a screenshot to this PR so I can see what the styling change looks like? Also as Ed mentions, it would be worth adding some guidance/documentation on the intended style going forward so that other teams can observe it. This could start off pretty light, and be further expanded as needed during development. The first version could simply be a new section in the README, with some documentation on fonts, font-sizes, primary and highlight colors for example.

**Review by ben-corbin — APPROVED** [review]

**Comment by nicopicchio** [comment]
image

**Review by mikemherron — CHANGES_REQUESTED** [review]
Looks good but see my previous comment - can we add something to the README to give the rest of the team some guidance on styling? Again, it can be quite light:

> Also as Ed mentions, it would be worth adding some guidance/documentation on the intended style going forward so that other teams can observe it. This could start off pretty light, and be further expanded as needed during development. The first version could simply be a new section in the README, with some documentation on fonts, font-sizes, primary and highlight colors for example.

**Comment by nicopicchio** [comment]
I have updated the readme file with some very light styling guidance. can anyone please review?

**Review by mikemherron — APPROVED** [review]

**Review by Auenc — APPROVED** [review]
Looks good to me!

**Pull request merged**
